In [1]:
import numpy as np

In [3]:
a=np.array([[1,0,0,1],[0,0,0,0]])

In [4]:
print(a)

[[1 0 0 1]
 [0 0 0 0]]


In [7]:
b=np.array([1,1,0,1])

In [11]:
np.matmul(a,b)

array([2, 0])

In [13]:
H=np.array([[0,0,0,1,1,1,1,0,1,0,1,1,0,0,1],[0,0,1,0,0,0,1,1,1,1,0,1,0,1,1],[0,1,0,0,0,1,1,1,1,0,1,0,1,1,0],[1,0,0,0,1,1,1,1,0,1,0,1,1,0,0],[0,1,1,0,0,0,1,1,0,0,0,1,1,0,0],[0,0,1,1,0,0,0,1,1,0,0,0,1,1,0],[0,0,1,0,1,0,0,1,0,1,0,0,1,0,1],[1,0,1,1,1,1,0,1,1,1,1,0,1,1,1]])

In [25]:
x=np.array([0,0,1,1,0,0,1,0,1,0,1,1,0,0,1])

In [26]:
y=list(np.matmul(H,x))

[x%2 for x in y]

[0, 1, 1, 0, 1, 1, 0, 1]